name: Build iOS
on: 
  workflow_dispatch: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          brew install autoconf automake libtool pkg-config
          python -m pip install --upgrade pip
          # Critical tools for the toolchain
          pip install "cython<3.0.0" buildozer kivy-ios packaging sh

      - name: Build with Buildozer
        run: |
          # Fix for Xcode 16 libarclite error
          export MACOSX_DEPLOYMENT_TARGET=13.0
          # We skip 'clean' to save time, but -v shows us errors if they happen
          buildozer -v ios debug
        env:
          BUILDOZER_WARN_ON_ROOT: 1

      - name: Upload Xcode Project
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-xcode-project
          # This path captures the compiled project
          path: .buildozer/ios/platform/kivy-ios/dist/hostpython3/
